name: AutoServerPaper
version: '${version}'
main: me.artificial.autoserver.papermc.AutoServerPaper
api-version: '${minecraft_version}'
load: STARTUP
author: '${author}'
description: '${description}'

commands:
  autoserver:
    description: AutoServer Backend root command.
    usage: /autoserver <subcommand>
    aliases: [as]