# AutoServer Configuration File

[messages]
# Prefix added to all messages displayed to the player.
prefix = "[<green>AutoServer<reset>] "

# Message displayed to the player when they attempt to connect to a server that is currently offline.
# %servername% will be replaced with the name of the backend server.
starting = "<red> %serverName% <reset> is not online. Server is starting you will be redirected when ready."

# Message displayed to the player if the server fails to start or cannot be connected to.
# %servername% will be replaced with the name of the backend server.
failed = "<red> Unable to connect you to %serverName%. Please try again later."

# Message displayed to the player when the server is ready, indicating that they will be connected shortly.
notify = "Server is ready you will be connected in 5 seconds..."



# Define servers here.
[servers]

# Example Configuration for a server named "survival".
[servers.survival]
# Command to start the "survival" server. Replace start command with your actual server start command.
start = 'start "" /D "C:\Users\MINECRAFT-SERVER\minecraft\servers\survival" cmd /c "start.bat"'
# Indicates whether this is a remote server.
remote = false

# Example Configuration for a server named "creative".
[servers.creative]
# Command to start and stop "creative" server.
# No local command since it is a remote server.
remote = true
# Port the remote server listens on for start command (default is 8080).
port = 8080